## Descripción del Problema:
Imagina que estás trabajando como analista de datos para una empresa que recopila información sobre las ventas diarias de diferentes productos en varias tiendas.

Necesitas analizar estos datos para extraer información útil y presentar un resumen de las ventas.

## Requisitos del Sistema:
* El programa debe generar datos de ventas de manera aleatoria para 10 productos diferentes en 5 tiendas distintas durante 7 días (una semana).
* Los datos deben estar almacenados en un array de NumPy de 3 dimensiones (productos, tiendas, días).
* Debes calcular y mostrar la siguiente información:
* Total de ventas por producto a lo largo de la semana.
* Total de ventas por tienda a lo largo de la semana.
* Promedio de ventas por producto por día.
* Promedio de ventas por tienda por día.
* Producto con mayor y menor ventas totales en la semana.
* Tienda con mayor y menor ventas totales en la semana.

## Detalles Específicos:
* Genera los datos de ventas aleatorias usando np.random.randint, con valores entre 0 y 100.
* Usa funciones de NumPy para calcular las sumas y promedios.
* Maneja posibles errores o valores inesperados.
* Presenta los resultados de manera clara y estructurada.

## Consideraciones Adicionales:
* Organiza tu código utilizando funciones para cada una de las tareas principales.
* Usa comentarios para explicar cada sección de tu código.
* Asegúrate de que el código sea robusto y maneje casos en los que los datos generados puedan estar fuera de los rangos esperados.

In [1]:
import numpy as np

def generar_datos_ventas(productos, tiendas, dias):
    # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    return np.random.randint(0, 101, (productos, tiendas, dias))

def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))

def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

def imprimir_resumen(estudiantes):
    # Imprime un resumen con el nombre de los estudiantes, su promedio y su estado
    pass

productos = 10
tiendas = 5
dias = 7

# Genera los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)
print(datos)
# Calcula los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

# Imprime los resultados
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

[[[ 95   9  20  39  73   0  29]
  [ 60  71  57  84  72  18  50]
  [ 93  30   5  16  25   9  80]
  [ 49  97  83  98  80  98  11]
  [ 30  79   7  84  30   2  30]]

 [[ 40  56  42  14   1  59 100]
  [ 36  99  98  54  96  24  90]
  [ 50  15  30  53   1  17  68]
  [ 38  71  40  75  72  33   8]
  [ 18   0  80  58  55  85  62]]

 [[ 71  89  75 100  46  46  56]
  [ 81  96  26  88  55   9  91]
  [ 98  16  77  32   2  61  67]
  [ 98  21  68  32  25  19  62]
  [ 86  97  80  97  51  97  11]]

 [[ 61  57  20  46  51   8  44]
  [ 84  61  43  15  94  73  78]
  [100  15  42  18  87  46  43]
  [ 95  83  25  59  84  26  21]
  [ 25  44  67  72  64  95 100]]

 [[ 40  71  50  88  38  60  91]
  [ 49  34  51 100  28  42  38]
  [ 95  91  56  68  38  88  93]
  [ 87  77  53  41  51  80  53]
  [ 92  88   0  40   3  73  80]]

 [[ 33  96  35  21  56  52  62]
  [ 22  36  16  50  59   1  57]
  [ 65  81  59  96  22  47  28]
  [ 43  91  62  50  91  69   7]
  [ 82  14  68  60  93  53  17]]

 [[ 25   7  81  90   1  69  